rules:
  - id: clinical-security-best-practices
    patterns:
      - pattern: $X = input()
    message: No uses input() sin validaci√≥n
    severity: ERROR
    languages: [python]
    metadata:
      category: security
      technology: python
